name: Build & Send Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build Plugin
        run: mvn clean package

      # 🔥 Debug (optional, zeigt dir die Datei)
      - name: List files
        run: ls target

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ wenzelfelix28@gmail.com }}
          password: ${{ hvnk shfd rtgk rsxa }}
          subject: "WRN LifePlugin Build"
          to: ${{ wenzelfelix28@gmail.com }}
          from: WRN Build <${{ wenzelfelix28@gmail.com }}>
          body: "Dein Plugin wurde erfolgreich gebaut 🚀"
          attachments: target/*.jar